# Config file

# configuration for switching sgready device with one or two Shelly devices
shelly2sgready:
  use_all_4_states: true      # if true also set shelly_optional_states

  shelly_state_2_3:
    ip: 192.168.xxx.xx          # required
    port: 80                    # optional
    relay: 0                    # optional
    #username: admin             # optional
    #password: geheim            # optional

  # this shelly is optional; set use_all_4_states: false if second shelly is not used
  shelly_optional_states:
    ip: 192.168.xxx.xx          # required
    port: 80                    # optional
    relay: 0                    # optional
    #username: admin             # optional
    #password: geheim            # optional

# heatpump specific settings
heatpump:                       # optional
  interval: 60
  use_small_as_limit: false

  production_limit:
    extreme_low_price: 500
    low_price: 1000
    normal_price: 2000
    high_price: 3000
    extreme_high_price: 4000

  production_limit_small:
    extreme_low_price: 100
    low_price: 200
    normal_price: 400
    high_price: 500
    extreme_high_price: 600

  price_limit:
    extreme_low_price: 0.20
    low_price: 0.25
    normal_price: 0.36
    high_price: 0.40
    extreme_high_price: 0.45

  consumption_limit: 100
  consumption_hysteresis: 100

  battery_soc_limit:
    extreme_low_price: 10
    low_price: 20
    normal_price: 25
    high_price: 60
    extreme_high_price: 100
    hysteresis: 10

# How to access InfluxDB
influxdb:
  url:
  token:
  org: home

  # Which InfluxDB bucket to send measurements.
  # This can be useful to control different data-retention rules
  # alternatively use the "bucket" key if you want everything to be sent to the
  # same bucket
  # bucket_hr:  # high resulution
  # bucket_lr:  # low resolution
  # bucket_mr:  # medium resolution
  bucket: all_data


